In [1]:
import torch

In [2]:
x = torch.Tensor([1,2,3])

In [3]:
x

tensor([1., 2., 3.])

In [4]:
x[0]

tensor(1.)

In [5]:
x[2]

tensor(3.)

In [6]:
x.shape

torch.Size([3])

In [7]:
x + torch.Tensor([4,4,4])

tensor([5., 6., 7.])

In [8]:
x + 5

tensor([6., 7., 8.])

In [9]:
x + [5,5,5]

TypeError: unsupported operand type(s) for +: 'Tensor' and 'list'

In [12]:
x = torch.Tensor([[1,2,3],[4,5,6]])

In [13]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [14]:
x[0,1]

tensor(2.)

In [15]:
x[:1]

tensor([[1., 2., 3.]])

In [16]:
x[:,1]

tensor([2., 5.])

In [17]:
x = torch.randn((1,5))

In [18]:
x

tensor([[ 2.0987, -1.9584, -0.4810, -0.5923,  1.3231]])